Resposive branch
addisalemseifu/Portofolio-Desktop-Version__Rep pull request #1
Opened 2021-09-23 13:43 UTC by addisalemseifu

-Added index.HTML and style.css files with the right tags and styles.
-Created a README.md file with a detailed explanation of the project.
-Configured linters.
-Added a .gitignore file to ignore node_modules.

2021-09-23 14:33 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Addisalem Beidework, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
GitHub flow is followed. :heavy_check_mark:
README is professional. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-23 14:33 UTC, SajjadAhmad14 commented on .github/workflows/linters.yml
> +name: Linters
Please use all the files from [this](https://github.com/microverseinc/linters-config/tree/master/html-css) linter config.

2021-09-23 14:33 UTC, SajjadAhmad14 commented on style.css
> +@media (max-width: 483px) {
Please write value for min-width property in range of 992px - 1100px).

2021-09-23 14:33 UTC, SajjadAhmad14 commented on index.html
> +        <div class="main__wrapper">
Please use background images for the Headline section as decoration from the design page.

2021-09-23 14:33 UTC, SajjadAhmad14 commented on index.html
> +            <img class="img__class" id="pic__1" src="./img/pic1.png" alt="">
The image for the first project is broken. KIndly see the screenshot below as a reference
![image](https://user-images.githubusercontent.com/35504149/134526833-d52f7b24-7bc1-47f4-8430-c510b419eaf3.png)
.

2021-09-23 14:33 UTC, SajjadAhmad14 commented on index.html
> +                <button class="see-project">See Project</button>
Please use a bit of small padding for the `See Project` button. KIndly see the screenshot below for reference.
![btn](https://user-images.githubusercontent.com/35504149/134526924-1e470c48-417a-40ae-81d8-857d9fe0da22.png)

2021-09-23 14:33 UTC, SajjadAhmad14 commented on index.html
> +                    <h3 class="languages-title">Languages</h3>
Please add a `down arrow` on the very right side of `Languages` as it can be seen in the design.

2021-09-23 14:33 UTC, SajjadAhmad14 commented on index.html
> +    </section>
Please remove extra space from the bottom of the contact form. Kindly see the screenshot below for reference.
![extra](https://user-images.githubusercontent.com/35504149/134526997-8d2e839a-e67b-432e-80ca-912d2f8751fe.png)

2021-09-23 14:33 UTC, SajjadAhmad14 commented on index.html
> +            <form>
Please add form validations, `action`, and `post` attributes. Moreover please use `Formspree` to submit the message to user's email.

2021-09-24 07:13 UTC, mke2111 requested changes
### Hey @addisalemseifu, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-24 07:16 UTC, mke2111 commented on index.html
> +            <img class="img__class" id="pic__1" src="./img/pic1.png" alt="">
- [ ] As previously requested, fix the image of the first project on desktop screens,
![Screenshot from 2021-09-24 10-15-46](https://user-images.githubusercontent.com/65501535/134633913-71fc4c05-04f9-4d41-a412-09fc68492ab2.png)

2021-09-24 09:54 UTC, addisalemseifu commented
The broken picture is working on my machine I don't understand why it is appearing broken on the remote version.

2021-09-24 10:14 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Addisalem Beidework, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-28 08:49 UTC, merged